version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    env_file:
      - ./backend/src/config/secrets.env

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm start

volumes:
  node_modules:
